# -*- coding: utf-8 -*-
"""kmeansclustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18T0-5IZyGaGqrEa49rcTxfrVBxHqIepe

### **K MEANS CLUSTERING**
### **MENENTUKAN UMKM POTENSIAL KOTA BANDA ACEH**

Oleh : Furqan Hermawan

####**Upload Data set**

Data set diperoleh dari website Dinas Koperasi Dan UMKM Provinsi Aceh

*Selengkapnya dapat dilihat di* :http://datakumkm.acehprov.go.id/index.php/umkm
"""

from google.colab import files
files.upload()

"""####**Import Library**"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

"""####**Preprocessing**

*   **Data Frame**
"""

df = pd.read_csv('/content/usaha_kecil.csv')
#df = pd.read_csv('/content/usaha_menengah.csv')
#df = pd.read_csv('/content/usaha_mikro.csv')

df.head()

"""*   **Visualisasi pesebaran data berdasarkan aset dan omset**"""

plt.scatter(df['Omset'],df['Aset'])

"""*   **Scalling Data**

MinMaxScaler = Scaler tersebut membuat data berada pada rentang 0 -1
"""

from sklearn import preprocessing

minmax=preprocessing.MinMaxScaler().fit_transform(df[['Omset','Aset']])
minmax

"""####**K Means Clustering**"""

kmeans = KMeans(n_clusters=3, random_state=123)
kmeans.fit(minmax)

print(kmeans.cluster_centers_)

print(kmeans.labels_)
df['Cluster'] = kmeans.labels_
df

"""*   **Visualisasi**"""

fig, ax = plt.subplots()
sct = ax.scatter(minmax[:,1], minmax[:,0], s = 100,
c = df.Cluster, alpha = 0.5)
centers = kmeans.cluster_centers_
ax.scatter(centers[:,1], centers[:,0], c='blue', s=200, alpha=0.5);

plt.title("Hasil Clustering K means UMKM Banda Aceh")
plt.xlabel("Omset")
plt.ylabel("Aset")
plt.show()

"""####**Download CSV**"""

from google.colab import files
df.to_csv('hasil_UsahaKecil.csv')
#df.to_csv('hasil_UsahaMenengah.csv')
#df.to_csv('hasil_UsahaMikro.csv')   
files.download('hasil_UsahaKecil.csv')
#files.download('hasil_UsahaMenengah.csv')
#files.download('hasil_UsahaMikro.csv')